### ISSUE TITLE
Documentation says default is "topbeat" but role does not install it

### ISSUE THREAD

**Issue by ghost** [strootman/ansible-beats#4]
Hello,

My team has been using your role to install Topbeat through ansible-galaxy for a while, and we thank you for this.

Since a few days, we cannot install topbeat anymore, since it was removed from the supported list of beats flavors. Sadly, I didn't manage yet to find a workaround. That being said, I found out that the README still refers to Topbeat, while it cannot be installed anymore.

**Comment by ghost** [comment]
Note, I understaood afterwards that Topbeat has also been removed from the existing packages of elasticsearch 5.x (deployed by your role), so any reference to topbeat could be replaces by references to metricbeat.

**Comment by strootman** [comment]
@DavidPineauScality, my apologies for the delay. 
And it's good to know this role is getting some use!

You're right about `topbeat` going away. This is essentially a documentation issue that I hope is addressed by my most recent changes. 

There are some build errors, tracked in #5. 

I will be actively developing this role through the end of the year, and will do my best to document my intent both through the role's documentation as well as GH issues.

The `v5.x` update brought some much needed changes to make beat deployments more diverse.

I'm going to leave this issue open until COB Friday, but I think it has been addressed.

**Comment by ghost** [comment]
I indeed think this is solved now :) Thank you !
